const providersData = [
    {
        id: 1,
        name: "Kwame Adu",
        photo: "https://kimi-web-img.moonshot.cn/img/cdn.ghanaweb.com/39a2e0e00dfddbbf34c692e14303eb0a7a80631b.jpg",
        category: "carpentry",
        services: ["Custom Furniture", "Door Installation", "Roofing", "Cabinet Making"],
        rating: 4.9,
        reviews: 127,
        price: "GHS 80-120/hour",
        experience: "8 years",
        availability: "available",
        location: "Tamale Central",
        completedJobs: 89,
        specialties: ["Traditional Furniture", "Modern Designs", "Repairs"],
        tools: ["Power Tools", "Hand Tools", "Measuring Equipment"],
        certification: "NVTI Level II",
        description: "Experienced carpenter specializing in custom furniture and home renovations."
    },
    {
        id: 2,
        name: "Amina Ibrahim",
        photo: "https://kimi-web-img.moonshot.cn/img/ghanaeducation.org/1c06ca6e2b3bb7e37f9fb8813a3ab18efbea1fea.jpg",
        category: "welding",
        services: ["Metal Fabrication", "Structural Welding", "Gates & Fences", "Repairs"],
        rating: 4.8,
        reviews: 93,
        price: "GHS 90-150/hour",
        experience: "6 years",
        availability: "available",
        location: "Tamale Industrial",
        completedJobs: 76,
        specialties: ["Steel Fabrication", "Aluminum Work", "Industrial Welding"],
        tools: ["Arc Welder", "Gas Equipment", "Grinding Tools"],
        certification: "NVTI Level I",
        description: "Professional welder with expertise in metal fabrication and structural work."
    },
    {
        id: 3,
        name: "Abdul Rahman",
        photo: "https://kimi-web-img.moonshot.cn/img/www.theghanareport.com/431eaca3f591b5601e9e72b1cf45be7f82d44d6d.png",
        category: "plumbing",
        services: ["Pipe Installation", "Leak Repairs", "Drainage Systems", "Bathroom Fittings"],
        rating: 4.7,
        reviews: 156,
        price: "GHS 70-100/hour",
        experience: "10 years",
        availability: "busy",
        location: "Tamale South",
        completedJobs: 134,
        specialties: ["Residential Plumbing", "Commercial Systems", "Emergency Repairs"],
        tools: ["Pipe Wrenches", "Cutting Tools", "Testing Equipment"],
        certification: "NVTI Level II",
        description: "Licensed plumber with extensive experience in residential and commercial systems."
    },
    {
        id: 4,
        name: "Fatima Alhassan",
        photo: "https://kimi-web-img.moonshot.cn/img/static.wixstatic.com/135648978d93325b056ed80846de3bf82a5cdb6b.jpg",
        category: "electrical",
        services: ["Wiring Installation", "Electrical Repairs", "Safety Inspections", "Appliance Installation"],
        rating: 4.9,
        reviews: 89,
        price: "GHS 85-130/hour",
        experience: "7 years",
        availability: "available",
        location: "Tamale North",
        completedJobs: 67,
        specialties: ["Home Wiring", "Commercial Installations", "Safety Systems"],
        tools: ["Multimeter", "Wire Strippers", "Safety Equipment"],
        certification: "NVTI Level I",
        description: "Certified electrician specializing in safe, efficient electrical installations and repairs."
    },
    {
        id: 5,
        name: "Ibrahim Yakubu",
        photo: "https://kimi-web-img.moonshot.cn/img/vsctools.com/edc4f02044e0b2013851303d6618443001daf43a.jpg",
        category: "auto-repair",
        services: ["Engine Repair", "Electrical Systems", "Brake Service", "Maintenance"],
        rating: 4.6,
        reviews: 112,
        price: "GHS 100-180/hour",
        experience: "9 years",
        availability: "available",
        location: "Tamale East",
        completedJobs: 98,
        specialties: ["Engine Diagnostics", "Electrical Repairs", "Preventive Maintenance"],
        tools: ["Diagnostic Tools", "Mechanical Tools", "Lifting Equipment"],
        certification: "NVTI Level II",
        description: "Skilled auto mechanic with expertise in both mechanical and electrical repairs."
    },
    {
        id: 6,
        name: "Mariama Sule",
        photo: "https://kimi-web-img.moonshot.cn/img/www.sulzer.com/60d9bc00e084bf082b7a38d307616f657c5e6074.jpg",
        category: "construction",
        services: ["Building Construction", "Renovations", "Masonry", "Plastering"],
        rating: 4.8,
        reviews: 74,
        price: "GHS 120-200/hour",
        experience: "12 years",
        availability: "busy",
        location: "Tamale West",
        completedJobs: 45,
        specialties: ["Residential Building", "Commercial Construction", "Renovations"],
        tools: ["Construction Tools", "Measuring Equipment", "Safety Gear"],
        certification: "NVTI Level II",
        description: "Experienced construction professional specializing in quality building and renovation work."
    },
    {
        id: 7,
        name: "Yakubu Musa",
        photo: "https://kimi-web-img.moonshot.cn/img/kmtools.com/067424483834dbc0e17b906a363ea5a1730c0e3b.jpg",
        category: "tailoring",
        services: ["Custom Clothing", "Alterations", "Repairs", "Traditional Wear"],
        rating: 4.7,
        reviews: 201,
        price: "GHS 50-80/hour",
        experience: "15 years",
        availability: "available",
        location: "Tamale Central",
        completedJobs: 167,
        specialties: ["Custom Designs", "Traditional Smocks", "Quick Alterations"],
        tools: ["Sewing Machines", "Cutting Tools", "Measuring Tools"],
        certification: "NVTI Level I",
        description: "Master tailor with expertise in both modern and traditional garment making."
    },
    {
        id: 8,
        name: "Hassan Iddrisu",
        photo: "https://kimi-web-img.moonshot.cn/img/www.craftsman.com/347cabfeb076f614d3279c612db815854ba25530",
        category: "metalwork",
        services: ["Blacksmithing", "Tool Making", "Ornamental Work", "Repairs"],
        rating: 4.5,
        reviews: 67,
        price: "GHS 75-120/hour",
        experience: "20 years",
        availability: "available",
        location: "Tamale Industrial",
        completedJobs: 89,
        specialties: ["Traditional Blacksmithing", "Tool Fabrication", "Decorative Metalwork"],
        tools: ["Forge Equipment", "Anvil", "Hand Tools"],
        certification: "Traditional Master",
        description: "Traditional blacksmith with decades of experience in tool making and metalwork."
    }
];